= Hybrid Cloud on OpenShift

image:https://github.com/redhat-developer-demos/hybrid-cloud/workflows/backend/badge.svg[]
image:https://github.com/redhat-developer-demos/hybrid-cloud/workflows/frontend/badge.svg[]

== Overview

This is a demo to showcase applications distributed in different OpenShift clusters installed on public clouds, controlled by Skupper and consumed by a Frontend.

== Prerequisites

* At least 2 OpenShift Cluters (ideally installed on different public cloud providers)
* OpenShift CLI (oc) installed
* https://skupper.io/start/index.html#step-1-install-the-skupper-command-line-tool-in-your-environment[skupper cli] installed

NOTE: Tested with skupper 0.3.2 and OpenShift 4.x

== Deploy Services

=== Deploy the backend service to **ALL** your clusters:

[source, shell-session]
----
oc login https://api.cluster-1ccb.openshift.com:6443 #<1>
oc new-project hybrid-cloud-demo #<2>
oc apply -f openshift/quarkus-backend.yml -n hybrid-cloud-demo #<3>
oc set env deployment/hybrid-cloud-backend WORKER_CLOUD_ID={aws|azr|gcp|local} -n hybrid-cloud-demo #<4>
oc annotate service hybrid-cloud-backend skupper.io/proxy=http -n hybrid-cloud-demo #<5>
----
<1>
<2>
<3>
<4>
<5> Annotate the service so it is _"skkuper-aware"_

=== Deploy the frontend service to your **MAIN** cluster:

[source, shell-session]
----
oc apply -f openshift/quarkus-frontend.yml -n hybrid-cloud-demo
oc expose service hybrid-cloud-frontend -n hybrid-cloud-demo
----

=== Skupper Configuration

=== Set up Skupper in the *MAIN* cluster

In your *MAIN* cluster, init `skupper` and create the `connection-token`:

[source, shell-session]
----
skupper init --console-auth openshift -n hybrid-cloud-demo
----

Once done, after a while (~2 minutes), run the `skupper status -n hybrid-cloud-demo` command. You should have the following output:

[source, shell-session]
----
Skupper is enabled for namespace "hybrid-cloud-demo" in interior mode. It is not connected to any other sites.
----

See the status of the skupper pods.

[source, shell-session]
----
oc get pods -n hybrid-cloud-demo

NAME                                        READY   STATUS    RESTARTS   AGE
hybrid-cloud-backend-7d98785fd5-pn6vg       1/1     Running   0          156m
hybrid-cloud-frontend-5b5b6d6dc5-fm9fk      1/1     Running   0          149m
skupper-router-5bf975d558-46dn2             2/2     Running   0          2m6s
skupper-service-controller-54d8b7f4-jnr28   2/2     Running   0          2m2s
----

Finally, create a connection token:

----
skupper connection-token token.yaml -n hybrid-cloud-demo
----

=== Set up Skupper in the *OTHER* clusters

In *all the other clusters*, use the connection token created in the previous step:

[source, shell-session]
----
skupper init -n hybrid-cloud-demo
skupper connect token.yaml -n hybrid-cloud-demo
----

Everything is connected and ready to be used.

== Generate traffic

In your *MAIN* cluster, run the following command:

[source, shell-session]
----
./scripts/generate-traffic.sh http://$(oc get route hybrid-cloud-frontend -n hybrid-cloud-demo --template={{.spec.host}})
----